CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    currency NUMERIC,
    created_at TIMESTAMP DEFAULT now() NOT NULL,
    CONSTRAINT username_chars CHECK (username ~ '^[a-z0-9_]+$'),
    CONSTRAINT username_length CHECK (char_length(username) BETWEEN 3 AND 20)
);

CREATE TABLE players (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    value NUMERIC NOT NULL,
    capacity INTEGER NOT NULL,
    slug TEXT UNIQUE
);

CREATE TABLE nba_players (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    type VARCHAR(4) NOT NULL,
    quantity NUMERIC(18,6) NOT NULL CHECK (quantity > 0),
    price NUMERIC(18,6) NOT NULL CHECK (price >= 0),
    "timestamp" TIMESTAMPTZ DEFAULT now() NOT NULL,
    CONSTRAINT transactions_type_check CHECK (type IN ('BUY', 'SELL'))
);

CREATE TABLE holdings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    player_id INTEGER,
    bought_for NUMERIC NOT NULL,
    buy_date TIMESTAMPTZ DEFAULT now(),
    quantity REAL,
    sold_for NUMERIC,
    sell_date TIMESTAMPTZ,
    active BOOLEAN DEFAULT true
);

CREATE TABLE player_price_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    "timestamp" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE nba_career_stats (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL UNIQUE,
    games_played INTEGER DEFAULT 0,
    points_per_game NUMERIC(5,2) DEFAULT 0,
    rebounds_per_game NUMERIC(5,2) DEFAULT 0,
    assists_per_game NUMERIC(5,2) DEFAULT 0,
    steals_per_game NUMERIC(5,2) DEFAULT 0,
    blocks_per_game NUMERIC(5,2) DEFAULT 0,
    field_goal_pct NUMERIC(4,3) DEFAULT 0,
    three_point_pct NUMERIC(4,3) DEFAULT 0,
    free_throw_pct NUMERIC(4,3) DEFAULT 0,
    minutes_per_game NUMERIC(5,2) DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    points_total NUMERIC(10,2) DEFAULT 0,
    rebounds_total NUMERIC(10,2) DEFAULT 0,
    assists_total NUMERIC(10,2) DEFAULT 0,
    steals_total NUMERIC(10,2) DEFAULT 0,
    blocks_total NUMERIC(10,2) DEFAULT 0,
    minutes_total NUMERIC(10,2) DEFAULT 0
);

CREATE TABLE nba_season_stats (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL,
    season VARCHAR(10) NOT NULL,
    games_played INTEGER DEFAULT 0,
    total_points INTEGER DEFAULT 0,
    total_rebounds INTEGER DEFAULT 0,
    total_assists INTEGER DEFAULT 0,
    total_steals INTEGER DEFAULT 0,
    total_blocks INTEGER DEFAULT 0,
    points_per_game NUMERIC(5,2) DEFAULT 0,
    rebounds_per_game NUMERIC(5,2) DEFAULT 0,
    assists_per_game NUMERIC(5,2) DEFAULT 0,
    steals_per_game NUMERIC(5,2) DEFAULT 0,
    blocks_per_game NUMERIC(5,2) DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (player_id, season)
);

CREATE TABLE nba_weekly_stats (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL,
    season VARCHAR(10) NOT NULL,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    games_played INTEGER DEFAULT 0,
    total_points INTEGER DEFAULT 0,
    total_rebounds INTEGER DEFAULT 0,
    total_assists INTEGER DEFAULT 0,
    total_steals INTEGER DEFAULT 0,
    total_blocks INTEGER DEFAULT 0,
    points_per_game NUMERIC(5,2) DEFAULT 0,
    rebounds_per_game NUMERIC(5,2) DEFAULT 0,
    assists_per_game NUMERIC(5,2) DEFAULT 0,
    steals_per_game NUMERIC(5,2) DEFAULT 0,
    blocks_per_game NUMERIC(5,2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (player_id, week_end)
);

CREATE TABLE player_nba_mapping (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL UNIQUE,
    nba_player_id INTEGER NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);






CREATE FUNCTION record_player_price_change() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.value IS DISTINCT FROM OLD.value THEN
        INSERT INTO player_price_history (player_id, price, "timestamp")
        VALUES (NEW.id, NEW.value, now());
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_record_price_change
AFTER UPDATE OF value ON players
FOR EACH ROW
EXECUTE FUNCTION record_player_price_change();






CREATE MATERIALIZED VIEW positions_mv AS
SELECT
    user_id,
    asset_id,
    SUM(CASE WHEN type = 'BUY' THEN quantity ELSE -quantity END) AS quantity,
    CASE
        WHEN SUM(CASE WHEN type = 'BUY' THEN quantity ELSE 0 END) > 0
        THEN
            SUM(CASE WHEN type = 'BUY' THEN quantity * price ELSE 0 END)
            / SUM(CASE WHEN type = 'BUY' THEN quantity ELSE 0 END)
        ELSE 0
    END AS average_cost
FROM transactions
GROUP BY user_id, asset_id
HAVING SUM(CASE WHEN type = 'BUY' THEN quantity ELSE -quantity END) > 0
WITH NO DATA;





CREATE INDEX idx_transactions_user_id ON transactions(user_id);
CREATE INDEX idx_transactions_asset_id ON transactions(asset_id);
CREATE INDEX idx_transactions_timestamp ON transactions("timestamp");

CREATE INDEX idx_player_price_history_player_timestamp
ON player_price_history(player_id, "timestamp" DESC);

CREATE INDEX idx_positions_mv_user_asset
ON positions_mv(user_id, asset_id);








ALTER TABLE transactions
    ADD CONSTRAINT transactions_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE transactions
    ADD CONSTRAINT transactions_asset_id_fkey
    FOREIGN KEY (asset_id) REFERENCES players(id);

ALTER TABLE holdings
    ADD CONSTRAINT holdings_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE holdings
    ADD CONSTRAINT holdings_player_id_fkey
    FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;

ALTER TABLE player_price_history
    ADD CONSTRAINT player_price_history_player_id_fkey
    FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;

ALTER TABLE nba_career_stats
    ADD CONSTRAINT nba_career_stats_player_id_fkey
    FOREIGN KEY (player_id) REFERENCES nba_players(id) ON DELETE CASCADE;

ALTER TABLE nba_season_stats
    ADD CONSTRAINT nba_season_stats_player_id_fkey
    FOREIGN KEY (player_id) REFERENCES nba_players(id) ON DELETE CASCADE;

ALTER TABLE nba_weekly_stats
    ADD CONSTRAINT nba_weekly_stats_player_id_fkey
    FOREIGN KEY (player_id) REFERENCES nba_players(id) ON DELETE CASCADE;

ALTER TABLE player_nba_mapping
    ADD CONSTRAINT player_nba_mapping_player_id_fkey
    FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE;

ALTER TABLE player_nba_mapping
    ADD CONSTRAINT player_nba_mapping_nba_player_id_fkey
    FOREIGN KEY (nba_player_id) REFERENCES nba_players(id) ON DELETE CASCADE;
